checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: [src/*]

build:
    environment:
        php:
            version: 5.5.25
    tests:
        override:
            -
                command: 'bin/phpunit --coverage-clover coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
