checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: [src/*]

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
