language: php

php:
    - 5.6
    - 5.5

install:
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash
    - composer install

script:
    - mkdir -p build/logs
    - phpcs --standard=psr2 src
    - bin/phpunit --coverage-text
